'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LogiBlocks_Server.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''
        '''
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=windows-1252&quot;&gt;
        '''    &lt;meta http-equiv=&quot;Cache-Control: max-age=0, must-revalidate&quot; content=&quot;public&quot;&gt;
        '''    &lt;title&gt;Dark Nebula&lt;/title&gt;
        '''&lt;/head&gt;
        '''&lt;body oncontextmenu=&quot;return false&quot;&gt;
        '''    &lt;style type=&quot;text/css&quot;&gt;
        '''        body {
        '''            margin-top: 0px;
        '''            margin-bottom: 0px;
        '''            margin-left: 0px;
        '''            margin-right: 0px;
        '''            padding: 0;
        '''            overflow: hidden;
        '''       [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Index() As String
            Get
                Return ResourceManager.GetString("Index", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to var http = require(&apos;http&apos;);
        '''var fs = require(&apos;fs&apos;);
        '''var url = require(&apos;url&apos;);
        '''var os = require(&apos;os&apos;);
        '''var clientids = 0
        '''var interfaces = os.networkInterfaces();
        '''var addresses = [];
        '''for (var k in interfaces) {
        '''    for (var k2 in interfaces[k]) {
        '''        var address = interfaces[k][k2];
        '''        if (address.family === &apos;IPv4&apos; &amp;&amp; !address.internal) {
        '''            addresses.push(address.address);
        '''        }
        '''    }
        '''}
        '''var portnum = 8081
        '''var serverip = addresses.toString()
        '''// Create a server
        '''http.createServer( function [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property server() As String
            Get
                Return ResourceManager.GetString("server", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
